  slack_bot:
    build: .
    links:
     - mongo 
    environment:
      PYTHON_FILE: slack_client
    ports:
      - "443:443" 
  bitcoin_loader:
    build: .
    links:
     - mongo
    environment:
      PYTHON_FILE: bitcoin_loader
    restart: always
  mongo:
    image: mongo 
    ports:
      - "27017:27017"
    restart: always
