  bot:
    build: .
    links:
     - mongo 
    environment:
      PYTHON_FILE: slack_bot
    ports:
      - "443:443"
  socket:
    build: .
    links:
     - mongo 
    environment:
      PYTHON_FILE: service
    ports:
      - "5000:5000" 
  bitcoin_loader:
    build: .
    links:
     - mongo
    environment:
      PYTHON_FILE: bitcoin_loader
    restart: always
  mongo:
    image: mongo 
    ports:
      - "27017:27017"
    restart: always
  client:
   image: nginx
   ports:
     - "4040:80"
   volumes:
     - "./client/technicalanalysis/www:/usr/share/nginx/html"
   restart: always
